<a href="https://colab.research.google.com/github/danush-95/1D-axisymmetric-element/blob/master/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




## **Import the necessary libraries**




In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


## Read the dataset

In [52]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv')
X_features = df.iloc[:,:-1].values
Y_features = (df.iloc[:,-1].values)

print(X_features.shape)
print(Y_features)

(10, 3)
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## **Account for missing data**

In [53]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X_features[:, 1:] = imputer.fit_transform(X_features[:, 1:])
print(X_features)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**Encode the dataset**

In [54]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_features = ct.fit_transform(X_features)
#print(X_features)
label_encoding = LabelEncoder()
Y_features = label_encoding.fit_transform(Y_features)
#print(Y_features)

**Split the dataset**

In [55]:
x_train, x_test, y_train, y_test = train_test_split(X_features,Y_features, test_size=0.2, random_state=42, shuffle=True)

print("X_train_set: ", x_train)
print("Y_tain_set : ", y_train)
print("X_test_set : ", x_test)
print("Y_test_Set : ", y_test)

X_train_set:  [[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]
Y_tain_set :  [1 0 1 0 1 1 0 0]
X_test_set :  [[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]]
Y_test_Set :  [0 1]


**Feature scaling**

In [57]:
st = StandardScaler()
x_train[:, 3:] = st.fit_transform(x_train[:, 3:])
x_test[:, 3:] = st.transform(x_test[:, 3:])
